git submodule add https://github.com/ervandew/ag bundle/ag
git submodule add https://github.com/vim-scripts/AutoComplPop.git bundle/AutoComplPop 
git submodule add https://github.com/flazz/vim-colorschemes.git bundle/vim-colorschemes
git submodule add https://github.com/lrvick/Conque-Shell.git bundle/Conque-Shell
git submodule add https://github.com/vim-scripts/cscope-quickfix bundle/cscope-quickfix
git submodule add https://github.com/kien/ctrlp.vim.git bundle/ctrlp.vim
git submodule add https://github.com/davidhalter/jedi-vim.git bundle/jedi-vim
git submodule add https://github.com/tomasr/molokai.git bundle/molokai
git submodule add https://github.com/yegappan/mru.git bundle/mru
git submodule add https://github.com/scrooloose/nerdtree.git bundle/nerdtree
git submodule add https://github.com/rkulla/pydiction.git bundle/pydiction
git submodule add https://github.com/luochen1990/rainbow.git bundle/rainbow
git submodule add https://github.com/msanders/snipmate.vim.git bundle/snipmate.vim
git submodule add https://github.com/vim-scripts/TaskList.vim bundle/TaskList
git submodule add https://github.com/tomtom/tcomment_vim.git bundle/tcomment_vim
git submodule add https://github.com/gabesoft/vim-ags bundle/vim-ags
git submodule add https://github.com/bling/vim-airline bundle/vim-airline
git submodule add https://github.com/alvan/vim-assistant.git bundle/vim-assistant
git submodule add https://github.com/ConradIrwin/vim-bracketed-paste bundle/vim-bracketed-paste 
git submodule add https://github.com/flazz/vim-colorschemes.git bundle/vim-colorschemes
git submodule add git://github.com/altercation/vim-colors-solarized.git bundle/vim-colors-solarized
git submodule add https://github.com/Lokaltog/vim-distinguished.git bundle/vim-distinguished
git submodule add https://github.com/tpope/vim-fugitive.git bundle/vim-fugitive
git submodule add https://github.com/freeo/vim-kalisi.git bundle/vim-kalisi
git submodule add https://github.com/git-mirror/vim-l9.git bundle/vim-l9
git submodule add git://github.com/tpope/vim-projectionist.git bundle/vim-projectionist
git submodule add https://github.com/ghewgill/vim-scmdiff.git bundle/vim-scmdiff
git submodule add https://github.com/duff/vim-scratch bundle/vim-scratch 
git submodule add https://github.com/kshenoy/vim-signature.git bundle/vim-signature
git submodule add https://github.com/tpope/vim-surround bundle/vim-surround 
git submodule add https://github.com/bronson/vim-trailing-whitespace bundle/vim-trailing-whitespace 
git submodule add git://github.com/tpope/vim-unimpaired.git bundle/vim-unimpaired
